### ISSUE TITLE
Add functionality to bulky

### ISSUE THREAD

**Issue by kodi-rc** [linuxmint/bulky#15]
Try using the Windows application CKRename has very interesting options for renaming files that I didn't find in bulky and that would be interesting to be implemented:

-replace all filenames with a new default name
-insert batch auto-numbering at the beginning or end of the name, with initial value, increment and leading zeros
-change extensions in batch or remove them

https://www.softpedia.com/get/System/File-Management/CKRename.shtml
This CKRename is very simple and intuitive to use by commoners, who don't know regular expressions.

<img src='https://windows-cdn.softpedia.com/screenshots/CKRename_1.png' border='0' alt='CKRename-1'/>

----

imagine a directory with several pictures with random names and I want to rename them to: 
2021_Niver_001.jpg
2021_Niver_002.jpg ...

I couldn't do this in bulky, but in CkRename it's very easy

**Comment by smurphos** [comment]
Sure you can

![2022-03-23_05-56](https://user-images.githubusercontent.com/29017677/159633367-66c5c086-dd17-464a-bb7b-ec6d0925f622.png)
