### ISSUE TITLE
Bug: Unable to add file/folder with space in name to bulky using CLI

### ISSUE THREAD

**Issue by fenilgmehta** [linuxmint/bulky#19]
Thanks a lot for developing this wonderful bulk file renamer.

- I am using version 1.7
- I am facing issue with adding files and folders with spaces in the name to bulky using CLI. They get added if I launch bulky from the desktop entry and use the `+` button.
![image](https://user-images.githubusercontent.com/42742240/131740536-69c1bea3-d725-4f61-b149-00accb141f67.png)

**Comment by mtwebster** [comment]
I'm pretty certain this is fixed already, we just need to get a release out with the fixes. If you want to try, you can download this file:
https://github.com/linuxmint/bulky/blob/master/usr/lib/bulky/bulky.py

and copy it over the one in `/usr/lib/bulky`on your system.

**Comment by fenilgmehta** [comment]
Initially it was not showing any error.

After downloading the latest file and copying it to `/usr/lib/bulky` like you suggested, it is throwing an error. Please have a look at the below image.
![image](https://user-images.githubusercontent.com/42742240/131798343-be7ecf7b-9add-4d93-a193-9789c06872b9.png)

I edited the lasted `bulky.py` and added `print(sys.argv)` in the `load_files` method. And, it printed the following.
![image](https://user-images.githubusercontent.com/42742240/131798720-e504e10b-efc0-4d88-854b-ef10e8d44c7e.png)

The data in `sys.argv` is incorrect. I have never seen such an issue with `sys.argv` before.

**Comment by fenilgmehta** [comment]
If I use `/usr/bin/python3 /usr/lib/bulky/bulky.py 'a b'` to launch bulky, then it works correctly
![image](https://user-images.githubusercontent.com/42742240/131799441-84259f95-8303-4721-8e5a-a79bf12d7d82.png)

**Comment by fenilgmehta** [comment]
Thanks🙏, it is working properly after this change

**Comment by fenilgmehta** [comment]
- I will leave the issue open for tracking purpose
- Someone can update [https://github.com/linuxmint/bulky/blob/master/usr/bin/bulky](https://github.com/linuxmint/bulky/blob/master/usr/bin/bulky) and close the issue.
