### ISSUE TITLE
How do I bulit it?

### ISSUE THREAD

**Issue by singaltanmay** [linuxmint/bulky#23]
Hello devs! I am new to Linux app development and have no idea how to build and run bulky on my computer.

I tried running various bash and python scripts but no luck

I ran `make` in the root directory of the repo and got 

```
Building the mo files
# WARNING: the second sed below will only works correctly with the languages that don't contain "-"
for file in `ls po/*.po`; do \
        lang=`echo $file | sed 's@po/@@' | sed 's/\.po//' | sed 's/bulky-//'`; \
        install -d usr/share/locale/$lang/LC_MESSAGES/; \
        msgfmt -o usr/share/locale/$lang/LC_MESSAGES/bulky.mo $file; \
done \

```

This is my `uname -a` if that makes a difference
`Linux fedora 5.13.14-200.fc34.x86_64 #1 SMP Fri Sep 3 15:33:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bebo-dot-dev** [comment]
https://github.com/linuxmint/bulky/issues/24

This works on Linux Mint, not sure about Fedora.

**Comment by clefebvre** [comment]
https://linuxmint-developer-guide.readthedocs.io/en/latest/building.html
