### ISSUE TITLE
Enhancement request: drag & drop files from filemanagers

### ISSUE THREAD

**Issue by ghost** [linuxmint/bulky#30]
This would really reduce the time needed to perform a renaming.

**Comment by guenam** [comment]
I just discovered that, on Nemo, there is a preference in Behavior > Bulk Rename. If bulky is indicated, one can select several files on Nemo, hit F2 and these files "auto-load" in Bulky eg "File Renamer" in Mint 20.2 (and maybe previous versions, idk). 

That's a great alternative to Drag & Drop, but I never figured it despite using Nemo for... years. Maybe it's on me, idk. This might be a reason to close the request ; however Drag & Drop is ubiquitous and therefore just expected to work ; Mint's idea is to look familiar to others OS users, isn't it?  I'll let the Mint team decide to close this request or not.

**Comment by xenopeek** [comment]
You can also select multiple files in Nemo (or Caja, on MATE), right-click and choose "Rename..." to load them in Bulky. This is new functionality in Linux Mint 20.2. It was covered in the "New Features" for that release.

**Comment by andrewdbate** [comment]
For those finding this issue who are using Bulky and Nemo on something other than Linux Mint (e.g., elementary OS), to be able to bulk rename with Nemo, you need to open Nemo then go to Edit > Preferences > Behavior and enter `bulky` as the bulk rename command. This is the default configuration in Linux Mint 20.2.

Then you will be able to bulk rename files from Nemo by selecting multiple files, right-clicking and choosing "Rename...".

However, drag and drop support would still be welcome.
