### ISSUE TITLE
Fails to find final Dot in Folder names

### ISSUE THREAD

**Issue by MidnightDriveApps** [linuxmint/bulky#35]
In all modes I've tried, the final dot in a folder name is never matched:

![Screenshot from 2022-01-19 12-18-56](https://user-images.githubusercontent.com/51298318/150207583-af9c2321-d0fd-4d23-b4cd-360617f217b1.png)

Regex failing to match to last instance of DOT in folder names only:

![Screenshot from 2022-01-19 12-12-05](https://user-images.githubusercontent.com/51298318/150206818-a365c654-6b23-429d-a586-eb68827ece22.png)

This occurs regardless of selecting "Name only" or "Name and Extension", as well as attempting to match only the dot itself:
![Screenshot from 2022-01-19 12-17-31](https://user-images.githubusercontent.com/51298318/150207324-5c910046-b1b2-4162-8ecf-0ec697aa8ab6.png)

**Comment by fenilgmehta** [comment]
This issue has already been fixed in commit 582a086c9d4d909c4e07cbd2be74d3c427023923 (date 5 Aug 2021)
