### ISSUE TITLE
Title case conversion error

### ISSUE THREAD

**Issue by PHPeon** [linuxmint/bulky#36]
Words such as ain't or isn't will get capitalized as Ain'T.

**Comment by fenilgmehta** [comment]
It happens because of the way Python's built-in `str.title` function works ([bulky.py#L673](https://github.com/linuxmint/bulky/blob/bae3488fd6f6b347aef9dc09beea3de19a43814b/usr/lib/bulky/bulky.py#L673) `repo/usr/lib/bulky/bulky.py > class MainWindow > change_case(...)`).

Below is one of the way in which this issue can be fixed. However, I am not sure if this will break anything else or not.
```py
# Refer: https://stackoverflow.com/a/8347146
import re
WORD_RE = re.compile(r"[\w']+")

def capitalizeMatch(m):
  return m.group(0).capitalize()

def capitalizeWords(s):
  return WORD_RE.sub(capitalizeMatch, s)

print(capitalizeWords("isn't"))
print(capitalizeWords("this is cool, isn't it ?"))
```

**Comment by fenilgmehta** [comment]
The following link also gives a similar solution for this issue: https://www.pythontutorial.net/python-string-methods/python-titlecase/

**Comment by fenilgmehta** [comment]
@xenopeek, thanks for pointing the way `str.title` handles underscore.

How about using the `regex` library ?
```py
import regex
print(regex.findall(r"[[\w']&&[^_]]+", 'test_one', regex.VERSION1))
```

In the example code which I shared above, we just have to `import regex` and change `WORD_RE`
```py
# For capitalization functions refer: https://stackoverflow.com/a/8347146
# For regex intersection usage refer: https://stackoverflow.com/a/28783470
import regex
WORD_RE = regex.compile(r"[[\w']&&[^_]]+", regex.VERSION1)

def capitalizeMatch(m):
  return m.group(0).capitalize()

def capitalizeWords(s):
  return WORD_RE.sub(capitalizeMatch, s)

print(capitalizeWords("isn't"))  # Output = Isn't
print(capitalizeWords("this is cool, isn't it ?"))  # Output = This Is Cool, Isn't It ?
print(capitalizeWords('test_one'))  # Output = Test_One
```

How did you know about the way `str.title` handles underscore ? I could not find any details at https://docs.python.org/3/library/stdtypes.html#str.title

**Comment by xenopeek** [comment]
Looks like that works. Didn't know regex module could do that. I note that python3-regex isn't default installed on Linux Mint but it is available. It would be a new package dependency.

I didn't know about underscores at first. I looked up what the `\w` stood for exactly, saw also underscores and then wondered how `str.title` handled it. Tested it and here we are.

As I wrote, I don't know which is the better way to treat underscores: as words breaks or as part of words. Your first example may be fine even though it changes how underscores are treated. On the pros side it would use a standard module and not add a dependency.

What I should maybe have asked more explicitly: what do others think is the preferred way to treat underscores in filenames? Does it make most sense as currently to treat them as word breaks for title case change, or is it fine to treat them as part of words.

**Comment by fenilgmehta** [comment]
How about doing the title case conversion in two steps:
1. Update the case using `WORD_RE = re.compile(r"[\w']+")`
2. Find all index of `_` and change the case of the letters after the `_` to upper case

**Comment by fenilgmehta** [comment]
@xenopeek , the below code works
```py
# Refer: https://stackoverflow.com/a/8347146
import re

WORD_RE_1 = re.compile(r"[\w']+")
WORD_RE_2 = re.compile(r"_\w")

def capitalizeWords(s):
  res_1 = WORD_RE_1.sub(lambda m: m.group(0).capitalize(), s)
  res_2 = WORD_RE_2.sub(lambda m: m.group(0).upper(), res_1)
  return res_2

print(capitalizeWords("isn't"))
print(capitalizeWords("this is cool, isn't it ?"))
print(capitalizeWords("asdf_qwer_zxcv"))
```
