### ISSUE TITLE
Add renamer in numerical order

### ISSUE THREAD

**Issue by underailton** [linuxmint/bulky#38]
add renamer in numerical order, to rename numbers in sequence, example: 01, 02, 03, 03...

**Comment by jonathands** [comment]
> It's hidden pretty well, but it already exists. Once again, I was about to implement it because I didn't find it myself. Hover over the "replace" field, then it will show a tooltip saying how to do this.

I think this is a bug, in bulky.ui we have placeholder-text but that placeholder does not show on the UI
