### ISSUE TITLE
Insert at position x with overwrite fails to insert at correct position with short original filenames.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/bulky#39]
Bulky 2.1

I don't think the behaviour as shown in this screenshot is intended - it's certainly not intuitive.  I'd expect in this scenario for the insert position to remain position 6 for the two short filenames and the renamed filename length be increased to allow for the overwrite, rather than for the overwrite to start at an earlier position because of the short file size.

![2022-03-23_06-01](https://user-images.githubusercontent.com/29017677/159634303-03fc3377-9d05-4fd6-867a-5c63fddc4058.png)

It gets really silly with a longer insert string

![2022-03-23_06-06](https://user-images.githubusercontent.com/29017677/159634475-313cec27-e56d-4312-af28-72f9df9cb96a.png)

**Comment by fenilgmehta** [comment]
I think we just need to update one line ([bulky.py#664](https://github.com/linuxmint/bulky/blob/bae3488fd6f6b347aef9dc09beea3de19a43814b/usr/lib/bulky/bulky.py#L664)) to fix this issue
```py
# Search for the below line in the code and replace the statement under it with the below line of code:
#     if len(text) >= length
string[0:from_index] + text
```
