### ISSUE TITLE
[Bug] Crash when Replace text has \0 with capture groups

### ISSUE THREAD

**Issue by Alzarath** [linuxmint/bulky#44]
# Replicate
* Add a file to the File Renamer
* Enable "Regular expression"
* Enter a capture group into the "Find" field (Entering `()` is sufficient)
* Enter `\0` in the "Replace" field

# Expectation
Return entire matching regex
OR
Nothing

# Result
Bulky stalls with the terminal outputting "embedded null byte" indefinitely.

**Comment by fenilgmehta** [comment]
I think we can close this issue as it has been fixed with the pull request https://github.com/linuxmint/bulky/pull/47
@mtwebster

**Comment by Alzarath** [comment]
Confirmed.
