### ISSUE TITLE
Add enumeration feature to Bulky

### ISSUE THREAD

**Issue by antimatter84** [linuxmint/bulky#9]
When I use renaming tools, I often need to enumerate files. Such a feature would look good in Bulky.

Enumeration can be realised by entering an enumeration variable, e.g. %n into the field and some configuration (start number, stride, number of leading zeroes)

**Comment by mtwebster** [comment]
Hi, this is already supported - look at the tooltip for the Replace field: 

![Screenshot from 2021-07-11 08-53-26](https://user-images.githubusercontent.com/262776/125195894-c4e5e480-e225-11eb-979b-00e978dd4b98.png)

**Comment by kaoneko** [comment]
This feature apparently doesn't have high discoverability. I came here for the same reason as antimatter84, believing enumeration was not possible. I never saw the tooltip; when you click in the field it never shoes up, only when you hover over it without clicking. Needs better discoverability.

I guess it's also not possible to start enumeration at a different number than 1? (Without knowing regex, I guess with regex anything is possible...)

**Comment by antimatter84** [comment]
I agree with @kaoneko, the tooltip might not be the most intuitive solution to communicate the enumeration to the user.
And it also seems to only support zero-padding suitable for 4-digit numbers. Using printf syntax (eg. _%04d_) can be a good improvement.

Nonetheless, adding a mass renamer to Linux Mint is a great thing. I like it very much.

**Comment by Draconicrose** [comment]
While the feature doesn't have good discoverability, a help document would certainly help. I first tried looking under the three dots menu for help, then Google, then I used the same menu to come here to GitHub and see if anyone else had suggested it already. 

Other than having a help file for Bulky, how about adding this tooltip text under the replace field?
